spring:
  application:
    name: solms

server:
  port: 8080

solms :
  host: tcps://mr-dacxxiat4dw.messaging.solace.cloud:55443
  vpn: kushdev-solace
  username: solace-cloud-client
  password: ENC(2uML3tSgLPclRaH0TSUqbNzzafqgazQ55CxEO6+rz7lOXYWbHXrOCSos89/ZczwCPSpM9JgbjianoJJl0tguGg==)
